PACKAGE_NAME="native-headset-battery"
PACKAGE_VERSION="0.2.0"

BUILT_MODULE_NAME[0]="headset_battery_test"
BUILT_MODULE_LOCATION[0]="kernel"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make -C kernel KDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C kernel clean"

AUTOINSTALL="yes"
